[tool.poetry]
name = "nbp-exchange-rates"
version = "0.1.0"
description = "Historical PLN exchange rates published by National Polish Bank"
authors = ["SlawCzech <slaw.czech@gmail.com>"]
license = "Beerware"
readme = "README.md"
packages = [{include = "nbp_exchange_rates"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "4.2.2"
pytest = "7.3.2"
pytest-django = "4.5.2"
pytest-cov = "4.1.0"
flake8 = "6.0.0"
flake8-django = "1.3"
black = "23.3.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"

python_files = ["test_*.py"]

addopts = [
   "--cov=.",
   "--cov-config=.coveragerc",
   "--cov-report",
   "term-missing:skip-covered",
   "--cov-fail-under=80"
]

[tool.black]
line-length = 120
target-version = ['py311']
exclude = '''
/(
    | \.git/  # exclude a directory
    | \.mypy_cache/  # exclude a directory
    | \.pytest_cache/  # exclude a directory
    | .*\.pyi?  # exclude generated files
    | .*\.json  # exclude metadata files
    | .*\.md  # exclude documentation
    | .*\.toml  # exclude configuration files
    | .*\.yml  # exclude configuration files
    | .*\.yaml  # exclude configuration files
    | .*\.txt  # exclude configuration files
    | .*\.lock  # exclude configuration files
    | .*\.sh  # exclude configuration files
    | .*\.log  # exclude configuration files
)/
'''

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
